### ISSUE TITLE
Implement ON UPDATE and ON DELETE with schemas

### ISSUE THREAD

**Issue by AliusDieMorietur** [metarhia/metasql#191]
Support `CASCADE`, `RESTRICT`, `NO ACTION`, `SET NULL`, `SET DEFAULT` for both `ON UPDATE` and `ON DELETE`

**Comment by tshemsedinov** [comment]
- [ ] For common reference fields: `entity: { type: 'Entity', delete: 'set null', update: 'set null' }`
- [ ] For many-to-many will be `{ many: 'Entity', delete: 'cascade', update: 'cascade' }` by default
