### ISSUE TITLE
Auto create Server

### ISSUE THREAD

**Issue by AliusDieMorietur** [metarhia/metasql#195]
We need `  await pool.query(
    INSERT INTO "Server" (
    "id",
    "name",
    "suffix",
    "ip",
    "ports"
  ) VALUES (
    $1,
    'mylovelyserver',
    'suffix',
    '127.0.0.1',
    '{"ports": [8001, 8002]}'
  ),
    [serverId]
  );`
   on db creation

**Comment by tshemsedinov** [comment]
Why?

**Comment by tshemsedinov** [comment]
This should be done from deploy script not a part of model generation
