### ISSUE TITLE
Support functions in select

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metasql#202]
Like `min`, `avg`, `sum`... Not `select('Entity', ['min("field")'])` will add quotes around function, so just check field list and don't add quotes.

**Comment by OleksiiKachan** [comment]
@tshemsedinov I'll work on this one

**Comment by tshemsedinov** [comment]
You have this in #167, I'll extract it to the separate commit and squash everything else there into separate one.

**Comment by OleksiiKachan** [comment]
@tshemsedinov I just check if field name has (. If you think that is enough then I'm good. cause I was thinking of instead of checking for (, check for function itself, like we do for operators <,>, <= and so on

**Comment by tshemsedinov** [comment]
Field can't contain `(` so it is ok
